# Primeiros passos Numpy

Exemplificando os diferentes tipos de arrays

In [1]:
import numpy as np

Array de apenas uma dimensão (1D array) é chamada de vetor ou vector.
Com duas dimensões são chamadas de matriz ou matrix (2D array).
Com três ou mais dimensões é chamada de tensor.

In [4]:
x1 = np.array([10, 9, 8, 7, 6, 5])

In [5]:
print (x1)

[10  9  8  7  6  5]


In [11]:
print('A variável x1 é do tipo:',type(x1))

print('A variável x1 tem ',x1.ndim,' dimensão.')

A variável x1 é do tipo: <class 'numpy.ndarray'>
A variável x1 tem  1  dimensão.


---------------------------------------------------------

In [49]:
zero = np.zeros(shape = (5,3,6))
print(zero)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [47]:
print('A variável x1 é do tipo:',type(zero))

print('A variável x1 tem ',zero.ndim,' dimensão.')

A variável x1 é do tipo: <class 'numpy.ndarray'>
A variável x1 tem  3  dimensão.


---------------------------------------------------------

arange podemos determinar o inicio (2), o fim (50) e uma constante que no caso usado foi para pular de 3 em 3

In [71]:
dez = np.arange(2,50,3)
print(dez)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


---------------------------------------------------------

Para uma sequência linear usamos o linspace
sintaxe np.linspace(start, stop, num = 50, endpoint = False, retstep = False, dtype = None, axis = 0)
 num = quantos números serão mostrados
 endpoint = False (o n° stop não será exibido)
 retstep = False (sendo false vai informar a constante entre um valor e o outro)
 

In [82]:
linear = np.linspace (1, 100, num = 20, retstep = True, dtype = None, axis = 0)

In [83]:
print(linear)

(array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ]), 5.2105263157894735)


---------------------------------------------------------

Concatenando arrays

In [86]:
x1 = np.array([5,6,7,8,9])
x2 = np.array([0,1,2,3,4])
y1 = np.concatenate((x1,x2))
y2 = np.concatenate((x2,x1))

In [95]:
print(y1)
print('-'*21)
print(y2)

[5 6 7 8 9 0 1 2 3 4]
---------------------
[0 1 2 3 4 5 6 7 8 9]


In [98]:
print(y2[y2>3])

[4 5 6 7 8 9]


In [101]:
print(max(y2))
print(min(x1))

9
5
